name: Validate Go solution
on:
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate-python:
    name: Validate Go solution
    runs-on: ubuntu-latest
    container: golang:1-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4     
      - name: Check Python version
        run: go version       
      - name: Install packages
        run: go mod download
        working-directory: ./src
